# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'DailyQuotes' do
  use_frameworks!

  # Pods for DailyQuotes

  pod 'DQCore', :path => 'DevPods/DQCore'
  pod 'DQCommon', :path => 'DevPods/DQCommon'
  pod 'DQAPILayer', :path => 'DevPods/DQAPILayer'

end
