# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'DailyQuotes' do
  use_frameworks!

  # Pods for DailyQuotes

  pod 'DQCore', :path => 'DevPods/DQCore'
  pod 'DQCommon', :path => 'DevPods/DQCommon'
  pod 'DQAPILayer', :path => 'DevPods/DQAPILayer'

  pod 'SVProgressHUD'
  pod 'NotificationBannerSwift'

#  target 'DailyQuotesWidgetExtension' do
#    use_frameworks!
##      inherit! :search_paths
#
#    pod 'DQAPILayer', :path => 'DevPods/DQAPILayer'
#  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end
  end

end
